CREATE OR REPLACE EDITIONABLE SYNONYM "C##DB_APP"."XT_USER" FOR "C##DB_XT"."XT_USER";
CREATE OR REPLACE EDITIONABLE SYNONYM "C##DB_APP"."XT_ROLE_MENU" FOR "C##DB_XT"."XT_ROLE_MENU";
CREATE OR REPLACE EDITIONABLE SYNONYM "C##DB_APP"."XT_USER" FOR "C##DB_XT"."XT_PERMISSION";

CREATE OR REPLACE EDITIONABLE SYNONYM "C##DB_APP"."DM_ARGUMENTS" FOR "C##DB_DM"."DM_ARGUMENTS";